name: code_generator
description: Provides interface/helper classes for implementing applications for generating code.
version: 0.1.0

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
